#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

#ifndef __cplusplus
#define UINT_MAX 4294967295
#endif

#define MAX_TEXTURES 512
#define TOTAL_MATERIALS 128 /// 127 Materials + IBL
#define BASIC_CHUNK_SIZE 256

#define LIGHT_TYPE_NONE 0u
#define LIGHT_TYPE_POINT_LIGHT 1u
#define LIGHT_TYPE_DIRECTIONAL_LIGHT 2u
#define LIGHT_TYPE_SPOT_LIGHT 3u

/// Task accumulate descriptor set layout defines
#define ACCUMULATE_PER_FRAME_LAYOUT_INDEX 0u

#define INCOMING_IMAGE_TO_SAMPLE 0u
#define ACCUMULATE_IMAGE_INDEX 1u
#define ESTIMATED_IMAGE_INDEX 2u

/// Task passthrough descriptor set layout defines
#define PASSTHROUGH_PER_FRAME_LAYOUT_INDEX 0u

#define PASSTHROUGH_TEXTURE_SAMPLER_LAYOUT_INDEX 0u

/// Task raytrace descriptor set layout defines
#define RAYTRACE_LAYOUT_INDEX 0u

#define RAYTRACE_TLAS_LAYOUT_INDEX 0u
#define RAYTRACE_RAYS_DATA_BUFFER 1u
#define RAYTRACE_RENDERABLE_BUFFER_INDEX 2u
#define RAYTRACE_HIT_BUFFER 3u
#define RAYTRACE_MATERIAL_INDEX_BUFFER 4u

/// Task clear image descriptor set layout defines
#define CLEAR_IMAGE_LAYOUT_INDEX 0u

#define IMAGE_TO_CLEAR 0u

/// Task shade descriptor set layout defines
#define COMPUTE_SHADE_LAYOUT_INDEX 0u

#define COMPUTE_SHADE_OUTPUT_IMAGE_INDEX 0u
#define COMPUTE_SHADE_MATERIAL_BUFFER_INDEX 1u
#define COMPUTE_SHADE_RENDERABLE_BUFFER_INDEX 2u
#define COMPUTE_SHADE_TRANSFORM_INDEX 3u
#define COMPUTE_SHADE_HITS_BUFFER_INDEX 4u
#define COMPUTE_SHADE_RAYS_BUFFER_INDEX 5u
#define COMPUTE_SHADE_IBL_IMAGE_INDEX 6u
#define COMPUTE_SHADE_TEXTURE_SAMPLER 7u
#define COMPUTE_SHADE_TEXTURE_ARRAY 8u
#define COMPUTE_SHADE_LIGHTS_BUFFER_INDEX 9u
#define COMPUTE_SHADE_MATERIAL_INDEX_MAP 10u
#define COMPUTE_SHADE_MATERIAL_INDEX_AOV_MAP 11u
#define COMPUTE_SHADE_MATERIALS_OFFSETS 12u

/// Task generate rays descriptor set layout defines
#define GENERATE_RAYS_LAYOUT_INDEX 0u

#define CAMERA_RAYS_BUFFER 0u
#define CAMERA_POSITION_BUFFER 1u

/// Task material sort count materials set layout defines
#define MATERIAL_SORT_COUNT_MATERIALS_PER_CHUNK_INDEX 0u

#define MATERIAL_SORT_COUNT_MATERIALS_MATERIAL_INDICES_AOV_BUFFER 0u
#define MATERIAL_SORT_COUNT_MATERIALS_MATERIAL_COUNT_BUFFER 1u

/// Task material sort clear materials count per chunk set layout defines
#define MATERIAL_SORT_CLEAR_MATERIALS_COUNT_PER_CHUNK_LAYOUT_INDEX 0u

#define MATERIAL_SORT_CLEAR_MATERIALS_COUNT_PER_CHUNK_BUFFER 0u

/// Task material sort clear total materials count set layout defines
#define MATERIAL_SORT_CLEAR_TOTAL_MATERIALS_COUNT_LAYOUT_INDEX 0u

#define MATERIAL_SORT_CLEAR_TOTAL_MATERIALS_COUNT_BUFFER 0u

/// Task material sort compute offsets per material set layout defines
#define MATERIAL_SORT_COMPUTE_OFFSETS_PER_MATERIAL_LAYOUT_INDEX 0u

#define MATERIAL_SORT_COMPUTE_OFFSETS_PER_MATERIAL_TOTAL_MATERIAL_COUNT_BUFFER 0u
#define MATERIAL_SORT_COMPUTE_OFFSETS_PER_MATERIAL_MATERIAL_OFFSETS_BUFFER 1u

/// Task material sort sort materials set layout defines
#define MATERIAL_SORT_SORT_MATERIALS_LAYOUT_INDEX 0u

#define MATERIAL_SORT_SORT_MATERIALS_MATERIALS_OFFSETS_PER_CHUNK_BUFFER 0u
#define MATERIAL_SORT_SORT_MATERIALS_MATERIAL_OFFSETS_PER_MATERIAL_BUFFER 1u
#define MATERIAL_SORT_SORT_MATERIALS_UNSORTED_MATERIALS_BUFFER 2u
#define MATERIAL_SORT_SORT_MATERIALS_SORTED_MATERIALS_INDEX_MAP_BUFFER 3u

/// Task material sort compute prefix sums us sweep set layout defines
#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_UP_SWEEP_LAYOUT_INDEX 0u

#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_UP_SWEEP_BUFFER_A 0u

/// Task material sort compute prefix sums zero out set layout defines
#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_ZERO_OUT_LAYOUT_INDEX 0u

#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_ZERO_OUT_BUFFER_A 0u
#define MATERIAL_SORT_TOTAL_MATERIAL_OFFSETS_BUFFER 1u

/// Task material sort compute prefix sums down sweep set layout defines
#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_DOWN_SWEEP_LAYOUT_INDEX 0u

#define MATERIAL_SORT_COMPUTE_PREFIX_SUMS_DOWN_SWEEP_BUFFER_A 0u

#endif // COMMON_DEFINES_H