#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

#define LIGHT_TYPE_NONE 0
#define LIGHT_TYPE_POINT_LIGHT 1
#define LIGHT_TYPE_DIRECTIONAL_LIGHT 2
#define LIGHT_TYPE_SPOT_LIGHT 3

/// Task accumulate descriptor set layout defines
#define ACCUMULATE_PER_FRAME_LAYOUT_INDEX 0

#define INCOMING_IMAGE_TO_SAMPLE 0
#define ACCUMULATE_IMAGE_INDEX 1
#define ESTIMATED_IMAGE_INDEX 2

/// Task passthrough descriptor set layout defines
#define PASSTHROUGH_PER_FRAME_LAYOUT_INDEX 0

#define PASSTHROUGH_TEXTURE_SAMPLER_LAYOUT_INDEX 0

/// Task descriptor indices
#define  RAYTRACE_LAYOUT_INDEX 0

#define  RAYTRACE_TLAS_LAYOUT_INDEX 0
#define  RAYTRACE_FINAL_IMAGE_INDEX 1
#define  RAYTRACE_RAYS_DATA_BUFFER 2
#define  RAYTRACE_RENDERABLE_BUFFER_INDEX 3
#define  RAYTRACE_MATERIAL_BUFFER_INDEX 4
#define  RAYTRACE_LIGHT_BUFFER_INDEX 5
#define  RAYTRACE_IBL_IMAGE_INDEX 6

#endif // COMMON_DEFINES_H